server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: java123456
    url: jdbc:postgresql://localhost:5432/registration
    username: java
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
